list_oftext = ("bragged about something I have not done.",
"I ever driven drunk.","I ever experimented to see my sexual orientation.",
"doubted in my heterosexuality.", "made fun of someone.",
 "watched keeping up with the Kardashians.", "said 'I love you' just to get laid.",
 "spied on my neighbours.", "Stole something with a higher value than $10.",
 "Really liked a song by Justin Bieber.", "bet on something.",
 "Done a handstand with one hand.", "stalked an ex's boyfriend or girlfriend on social media.",
 "Lied to a friend to avoid a greater evil.", "Escaped from class.",
 "had an open relationship.", "cheated on a test.", "grabbed the wrong person's hand.",
 "Fall in love with anyone through the network.", "Lied in this game.",
 "Said an 'I love you' without feeling it.", "Been kicked out of a bar.",
 "Entered into Facebook while drunk.", "Traveled by plane.",
 "Stuck gum under a desk.", "Bit my tongue.", "Stop remembering my first love.",
 "Done pictures in underwear.", "Refused a kiss.", "Been unfaithful.",
 "had a night stand.", "lied to my parents about being hung over.",
 "Gone to the bathroom and then not wash my hands.", "Kissed someone of the same sex.",
 "Swam naked in a pool / beach.", "Woken up drunk the next day.", "Got drunk.",
 "Kissed my best friend.", "Smoked marijuana.", "eaten food that fell on the floor.",
 "Got drunk playing these games.", "Kissed someone without knowing him/her.",
 "Screwed up at school.", "Been with the former love of my best friend.",
 "Seen a topless on the beach.", "had a friends with benefits.",
 "Fought in the street.", "Fallen asleep on the bus and I've passed my station.",
 "Been in love with my teacher in college.", "Been robbed.",
 "Received a serenade.", "Sneaked into a party.",
  "Wanted to fall in love with my sister's/brothers friend.",
  "Made love with someone from the university.", "Been stuck in a lift.",
  "Illegally taken something across the border.", "Lied to my parents about where I'm going.",
  "Finished an entire jawbreaker.", "Been in handcuffs.",
  "Fallen asleep in the cinema.", "Done something I regret.",
  "picked my nose in public.")
